/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
 // Accepted in 126ms
var findTheDifference = function(s, t) {
    var map={};
    for(var i=0;i<s.length;i++){
        if(map[s[i]] == null){
            map[s[i]] = 1;
        }
        else
        map[s[i]] =map[s[i]] +1;
    }
    
    for(var j=0;j<t.length;j++){
        if(map[t[j]] != null && map[t[j]] !=0)
        map[t[j]] = map[t[j]]-1;
        else
        return t[j];
    }
};